import Head from 'next/head'
import { Inter } from '@next/font/google'
import { colors, fonts } from '@/styles/theme'

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <h2>Hello there</h2>

      <style jsx>{`
        h2{
          color: ${ colors.grey };
          font-family: ${ fonts.base };
        }  
      `}</style>
    </>
  )
}
